### ISSUE TITLE
배민혁 백엔드 7주차 배포 과제 제출입니다.

### ISSUE THREAD

**Issue by bmh7190** [likelion-Inha-12/bmh7190#14]
![배포 성공](https://github.com/likelion-Inha-12/bmh7190/assets/81423073/f35871ac-413c-49b4-bcfa-779d3fceef3d)
![인스턴스 정보](https://github.com/likelion-Inha-12/bmh7190/assets/81423073/b475adbb-352d-4d5f-88ac-bf9e759c5231)

**Comment by juwon0403** [comment]
훌륭합니다 구웃!!!
배포 과정 꽤나 쉽지 않았을텐데 수고 많으셨서요~~
