### ISSUE TITLE
배민혁 8주차 백엔드 https, cors 과제 제출입니다.

### ISSUE THREAD

**Issue by bmh7190** [likelion-Inha-12/bmh7190#18]
![cors](https://github.com/likelion-Inha-12/bmh7190/assets/81423073/5f9e83b6-165c-44b3-b3fa-962ff4f4f6c8)

### 1. URL v.s. Origin v.s. Domain 각각의 개념은 무엇이고, 세 키워드 간의 관계는 어떻게 될까요?

- URL(Uniform Resource Locator)은 특정 자원(웹페이지, 이미지, 동영상 등)이 들어있는 웹페이지의 위치를 나타내는 주소이다.  프로토콜, 도메인 이름, 경로, 포트 번호, 쿼리 문자열 등을 포함할 수 있습니다.

- 도메인(Domain)은 인터넷에 연결된 컴퓨터의 ip를 사람이 쉽게 기억하기 어렵기 때문에 이를 위해서 각 ip에 사람이 쉽게 기억하고 입력할 수 있도록 문자(영문, 한글 등)로 만든 인터넷 주소이다. 주로 URL의 호스트 부분을 의미합니다.
도메인은 여러 계층으로 나눌 수 있으며, 최상위 도메인(TLD, 예: .com, .org), 2차 도메인(예: example), 서브도메인(예: www)을 포함합니다.

- Origin은 웹 페이지의 출처를 의미하며, 보안과 관련된 맥락에서 자주 사용됩니다. URL의 프로토콜, 호스트(도메인 이름), 포트 번호로 구성됩니다.

**URL은 웹 리소스의 전체 주소를 나타내고, 도메인은 URL의 호스트 부분을 나타내며, Origin은 보안을 위해 URL의 프로토콜, 호스트, 포트 번호를 포함하여 웹 리소스의 출처를 나타냅니다.** 

### 2. 같은 출처? 다른 출처?
| URL     | 결과 | 이유 |
|----------|-----|------------|
| https://lionz12.netlify.app/homework | 같은 출처 | URL의 프로토콜, 호스트,포트(기본 HTTPS 포트) 동일하다. |
| https://lionz12.netlify.app/homework-submit/69 | 같은 출처 | URL의 프로토콜,호스트, 포트(기본 HTTPS 포트)가 동일하다. |
| http://lionz12.netlify.app/homework | 다른 출처 | URL의 프로토콜이 다르다 |
| https://lionz12.seminar.com | 다른 출처 | URL의 호스트가 다르다. |

### 3. Access-Control-Allow-Origin : * 는 무슨 의미일지, 그리고 이렇게 설정한다면 무슨 일이 일어날지 생각해보세요!
Access-Control-Allow-Origin: *는 HTTP 헤더 중 하나로, 웹 서버가 특정 리소스에 대해 크로스 오리진 요청(Cross-Origin Requests)을 허용하는 것을 나타냅니다. 여기서 *는 모든 도메인에서의 요청을 허용한다는 의미입니다.

모든 도메인에서 리소스에 접근할 수 있기 때문에 악의적인 웹사이트도 데이터를 요청할 수 있습니다. 악의적인 사이트에서 사용자가 로그인한 세션을 이용해 요청을 보낼 수 있습니다. 이는 크로스 사이트 요청 위조(Cross-Site Request Forgery, CSRF) 공격을 더 쉽게 할 수 있게 만듭니다. 하지만 개발 단계에서 여러 도메인에서 API나 리소스를 쉽게 테스트할 수 있습니다. 이는 개발 속도를 높이고, 다양한 환경에서의 테스트를 가능하게 합니다. 또  리소스를 여러 도메인에서 활용할 수 있어, 다양한 클라이언트 애플리케이션이 동일한 백엔드를 사용할 수 있습니다.

### 5.  CORS와 같이 어플리케이션에서 사용자 정보를 탈취하는 것을 막기 위한 정책인 CSRF(Cross-Site Request Forgery)가 무엇인지, django에서는 CSRF 공격을 어떻게 방어하는지도 알아보면 좋을 것 같아요
CSRF란, Cross Site Request Forgery의 약자로, 인증된(권한을 가진) 사용자가 자신의 의도와 무관하게 공격자가 의도한 어떤 행위(수정, 삭제)를 하도록 유도하는 해킹 기법을 말한다. 간단한 예시로, 권한을 가진 사용자(즉 로그인한 사용자)에게 특정 악성 링크에 접속하도록 유도하고, 그 링크에 접속하면 자동으로 권한을 가진 웹사이트에 특정 POST 요청을 보내도록 설계하는 것을 들 수 있다. 즉, 자기도 모르게 (권한이 있어야만 수행할 수 있는) 위험한 요청을 서버에 보내도록 하는 것이다. 그러면 서버 입장에서는 권한이 있는 요청이라고 판단하여 요청된 동작을 그대로 수행할 것이다.

Django의 기본적인 CSRF 방지 메커니즘은 CSRF 토큰을 쿠키(세션이 아니라)에 저장하는 방식을 채택한다. 브라우저의 기본적인 보안 정책에 따르면, JavaScript를 이용하여 다른 도메인의 쿠키를 설정하는 것은 불가능하게 되어 있다. 따라서 임의의 난수로 생성한 CSRF 토큰을 쿠키로 전송함과 동시에 POST 파라미터 혹은 요청 헤더에 실어 보내고 서버에서는 그 둘이 같은지를 검사함으로써 유효성을 검증할 수 있게 된다.

**Comment by juwon0403** [comment]
깔끔하게 정리 잘해주셨네요!!
csrf 공격 방어하는 방법은 다른 아기사자분들 레포도 참고하면 더 도움이 되실 것 같습니당

과제하느라 수고하셨습니다~~
